name: 'Trans.ai'
description: 'Automated localization infrastructure'
author: 'trans'

inputs:
  api-key:
    description: 'Trans API key'
    required: true
  project-id:
    description: 'Trans project ID'
    required: true
  cli-version:
    description: 'Version of Trans CLI to use'
    required: false
    default: 'latest'
  dev-mode:
    description: 'Enable development mode'
    required: false
    default: 'false'
  create-pull-request:
    description: 'Create a pull request instead of committing directly'
    required: false
    default: 'false'
  commit-message:
    description: 'Custom commit message'
    required: false
  pr-title:
    description: 'Title for the pull request'
    required: false
  working-directory:
    description: 'Working directory relative to repository root'
    required: false

runs:
  using: 'docker'
  image: 'packages/action/Dockerfile'
  env:
    TRANS_API_KEY: ${{ inputs.api-key }}
    TRANS_PROJECT_ID: ${{ inputs.project-id }}
    TRANS_CLI_VERSION: ${{ inputs.cli-version }}
    TRANS_WORKING_MCPDATA: ${{ inputs.working-directory }}
    TRANS_CREATE_PULL_REQUEST: ${{ inputs.create-pull-request }}
    TRANS_COMMIT_MESSAGE: ${{ inputs.commit-message }}
    TRANS_PR_TITLE: ${{ inputs.pr-title }}
    DEV_MODE: ${{ inputs.dev-mode }}

branding:
  icon: 'git-merge'
  color: 'black'